name: Bug Report
description: "Report a general library issue."
body:
  - type: markdown
    attributes:
      value: "Before submitting your report, [please try updating to the latest version of Realoquent](https://packagist.org/packages/nova-horizons/realoquent)."
  - type: input
    attributes:
      label: Realoquent Version
      description: Provide the Realoquent version that you are using.
      placeholder: 0.1.0
    validations:
      required: true
  - type: input
    attributes:
      label: Laravel Version
      description: Provide the Laravel version that you are using.
      placeholder: 10.4.1
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
      description: Provide the PHP version that you are using.
      placeholder: 8.1.4
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System & Version
      description: Provide the operating system and version you are using.
      placeholder: "macOS 13.0"
    validations:
      required: true
  - type: input
    attributes:
      label: Database Type & Version
      description: Provide the type of database and version you are using.
      placeholder: "MariaDB 11.0.3"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true
