name: tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      #max-parallel: 1
      matrix:
        php: [ 8.3, 8.2, 8.1 ]
        laravel: [ 10.* ]
        testbench: [ 8.* ]
        dbal: [ 3.8.* ]
        include:
          - laravel: 10.*
            testbench: 8.*
    #          - laravel: 11.*
    #            testbench: 9.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - DBAL${{ matrix.dbal }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, pdo_pgsql, bcmath, soap, intl, exif, iconv
          coverage: pcov

      - name: Install dependencies
        run: composer update --with "illuminate/support:${{ matrix.laravel }}" --with "illuminate/database:${{ matrix.laravel }}" --with "doctrine/dbal:${{ matrix.dbal }}" --with "orchestra/testbench:${{ matrix.testbench }}" --no-interaction

      - name: Start Docker Databases
        run: |
          cp .env.example .env
          ./vendor/bin/sail up -d
          sleep 12

      - name: Run tests
        run: vendor/bin/pest --coverage-clover coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./coverage.xml
          verbose: true

      - name: Shutdown Docker Databases
        if: always()
        run: |
          ./vendor/bin/sail down --volumes
